### ISSUE TITLE
DB updating

### ISSUE THREAD

**Issue by RoyalGoose** [MariiaSizova/breakfastapi#1]
Is the database of recipes being updated or what is there now is this the final product?

**Comment by MariiaSizova** [comment]
Hey!
The database isn't being updated yet. At the moment it has 12.000 recipes I guess it should be enough for starters :)
In the future I will definitely make it updatable so that people can submit their own great recipes!
Thank you for bringing my attention to this. I will add some description of the database in Readme!

**Comment by RoyalGoose** [comment]
Thanks for your reply and your hard work. Also from the wishes, I would also like to see the composition of recipes for nutrients, if this is of course possible

**Comment by MariiaSizova** [comment]
Great idea with nutrients, thank you! Its a little tricky but for sure worth a try!
